### PR TITLE
Update to 0.6.0

### PR DESCRIPTION
**Pull request by thewtex**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewtex** [comment]
@conda-forge-admin, please rerender

**Comment by thewtex** [comment]
@conda-forge-admin, please rerender

**Comment by thewtex** [comment]
@ocefpaf @scopatz  I seem to have lost merge right on this repository even though I am a maintainer for it -- do you know how to fix that?

**Comment by ocefpaf** [comment]
That is odd. Let's try to update the team here.

@conda-forge-admin, please update team

**Comment by ocefpaf** [comment]
BTW, I can merge this for you so you don't have to wait.

**Comment by thewtex** [comment]
@ocefpaf thank you!

**Pull request merged**
